version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:
  redis-store:
  minio-store:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ../api
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
      - MAIL_HOST=mail
      - MAIL_PORT=1025
      - MAIL_USERNAME=${MAIL_USERNAME:-example_user}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-password}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-example}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-no-reply@example.com}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=develop
      - AWS_ENDPOINT=http://minio:9000


  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ../web
        target: /work/backend

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  mail:
    build:
      context: .
      dockerfile: ./infra/docker/mailhog/Dockerfile
    ports:
      - target: 8025
        published: ${MAIL_PORT:-8025}
        protocol: tcp
        mode: host

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-store:/data
      - type: volume
        source: redis-store
        target: /data
        volume:
          nocopy: true

  minio:
    image: minio/minio
    ports:
      - target: 9000
        published: ${MINIO_PORT:-9000}
        protocol: tcp
        mode: host
      - target: 9001
        published: ${MINIO_CONSOLE_PORT:-9001}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: minio-store
        target: /data
        volume:
          nocopy: true
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
